### ISSUE TITLE
a note on testing

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/SQL-bear-organizer#14]
For the "A Note on Testing" section: this needs to be clarified. Just delete whats there and replace it with a brief explanation of an in-memory database. Explain (briefly) this code from the test suite:

``` 
before do
    @db = SQLite3::Database.new(':memory:')
    @sql_runner = SQLRunner.new(@db)
    @sql_runner.execute_create_file
  end
```
explain that, before each test, it creates a shiny new in-memory database, creates a new instance of our SQLRunner class, which is a class we wrote to help connect to our database. The code in the test suite runs against our test/temporary/in-memory database. This keeps your real database separate from the test one.

**Comment by AnnJohn** [comment]
Closed by [PR #16](https://github.com/learn-co-curriculum/SQL-bear-organizer/pull/16)
