### ISSUE TITLE
encoded data

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/SQL-bear-organizer#15]
un-encode seed data, replace with a regular seed file and code that uses it to seed the database. explain part 3: to understand how the test suite works, check out the sqlrunner class. 

also move the sqlrunner class to spec folder.

**Comment by AnnJohn** [comment]
Closed by [PR #16](https://github.com/learn-co-curriculum/SQL-bear-organizer/pull/16)
