### ISSUE TITLE
Needs improvement on how to construct queries

### ISSUE THREAD

**Issue by marysue** [learn-co-curriculum/SQL-bear-organizer#38]
Simple queries were covered in previous sections, but more complex queries were not.  We need more information on constructing and deconstructing queries before we can perform this counting query.  What is the input to each operation within the query?  Where does the output flow to from each operation?

How do you analyze the query:

"SELECT color, count(*) FROM bears GROUP BY color ORDER BY (count(*)) DESC LIMIT 1;

Select color:  returns all of the colors that appear in each row.  Sort of obvious
Count(*):  counts what?
group by:  groups the colors -- this makes the output unique now, removing the duplicates
order by(count(*)) --> what is being fed into order by?  The count of what???  The count of the grouping? the count of all the colors???

How do you deconstruct the queries to understand what is the input from one, the output of the next?

**Comment by jenmyers** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
