### ISSUE TITLE
Lesson cannot be found

### ISSUE THREAD

**Issue by techtore** [learn-co-curriculum/SQL-bear-organizer#40]
[22:03:03] ~
// ♥ learn open SQL-bear-organizer-lab-online-web-ft-100719
Looking for lesson...
Hmm...Cannot find lesson with repo: sql-bear-organizer-lab-online-web-ft-100719. Please check your input and try again.

I tried cloning it manually and the folders and files were not populated.

**Comment by sgharms** [comment]
Hi there,

I looked at the main repository as well as the  sql-bear-organizer-lab-online-web-ft-100719 and have duplicated this issue. I'll be opening an issue with our technical team.
